### ISSUE TITLE
grunt-download-atom-shell does not work

### ISSUE THREAD

**Issue by karad** [karad/lein_template_descjop#1]
github repogitory moved atom/atom-shell -> atom/electon...

**Comment by karad** [comment]
wrote issue.

download fails because repository changed atom/atom-shell to atom/electon · Issue #22 · atom/grunt-download-atom-shell 
https://github.com/atom/grunt-download-atom-shell/issues/22

**Comment by ivyreese** [comment]
+1

For the time being, this fork of grunt-download-atom-shell works fine: https://github.com/simtel12/grunt-download-atom-shell/blob/update_for_electron_rename/tasks/download-electron-shell-task.coffee. Make sure you change the Gruntfile.js to version 0.24 and the task to download-electron-shell, and run ./atom-shell/Electron.app/Contents/MacOS/Electron app to launch the app.

By the way, thanks @karad for putting this template together (found it via the CLJ Google Group). I've been meaning to try using CLJS with NW.js, so getting to easily try Atom Shell (err... Electron) is going to be great for comparison.

**Comment by karad** [comment]
@ivanreese 
Thanks for advice! just grunt-download-electron https://github.com/atom/grunt-download-electron has been released. so, i released version 0.1.1. try it!!
