### ISSUE TITLE
Getting started problems

### ISSUE THREAD

**Issue by markjfisher** [karad/lein_template_descjop#15]
I'm not sure if it's meant to do this, but using a clean install of 0.5.2 project for both om and reagent give the results:

"X" does not work.

in the electron application when started (where X is "Om" for the om project, "Reagent" for the reagent project).

I'm on Mac OS/X.

Also, I'm firing up the figwheel listener as recommended using "lein trampoline figwheel frontend" which starts the autobuilder and says "Prompt will show when figwheel connects to your application", but I don't know how to get it to do that.

Going to "http://localhost:3449/index.html" gives "Cannot find:/index.html", presumably because of the figwheel_middleware.clj handler always returns a 404.

I think what I'm missing and what would be usefully documented are the next steps from a basic install for:
1. figwheel prompt working
2. any resources showing
3. om/reagent working in the electron window
4. an explanation of the link between figwheel and the electron app, for instance, do i need to run both at the same time for live code changes? If I only need to run figwheel, what URL do I go to in my browser to connect figwheel and see the browser version of the app? or doesn't it work like that?

Sorry for all the questions, but I'm still trying to piece together the parts and their interaction, plus because I'm getting "X does not work", i'm not sure if it's because I'm missing the next step, or the setup is broken, and how to go about fixing it.

**Comment by markjfisher** [comment]
I started using electron-template instead to see if I could get further and that worked out the box connecting the application to figwheel with changes reflected in the app and react working too, so this is really an issue that the default template for descjop doesn't work on my Mac OS/X. I'll close this, as I probably won't have chance to test it again in descjop.

**Comment by mping** [comment]
I wouldn't mind reopening this, since I have the same problem. I'm on Linux

**Comment by karad** [comment]
Thank you for report. 
I will reopen this issue, and start to investigate this probrem.

**Comment by rinconjc** [comment]
I had the same issue, then enabled dev-tools adding the below in core.cljs, and noticed that goog.require in index.html was referring to 'myproject-name.core' instead of 'myproject_name.core'. This fixed the problem.
;; enable dev tools
(.openDevTools @_win_)

**Comment by karad** [comment]
I fixed that problem. you can try new version descjop again! (new version has been available.)
