### ISSUE TITLE
Update template

### ISSUE THREAD

**Issue by gmp26** [karad/lein_template_descjop#25]
Many of the dependencies are now a long way behind and could do with an update. I would send a pull request but am hitting build issues after upgrade.

**Comment by gmp26** [comment]
The problem is with lein-figwheel. A change between lein-figwheel 0.5.4 and lein-figwheel 0.5.5 causes it to barf with "There are errors in your configuration file", and it is for some reason I can't fathom complaining about the :output-dir "app/dev/js/out" parameter.

**Comment by karad** [comment]
Thankyou for your comment! I'll fix the probrem and update descjop version.

**Comment by billrobertson42** [comment]
Suppose I create a project tonight, and then you do an update. Would I re-run the initialize steps from the README.md file?

**Comment by karad** [comment]
Released version 0.7.0.
The latest version will solve that problem.

**Comment by billrobertson42** [comment]
@karad Thanks for the new version. I'm sorry, when you say it will solve that problem, were you referring to my question? Does the plugin somehow actively look for new Electron versions? If so, is there a way to pin it to a specific version? Sorry if I'm missing something and these questions are just dense.

**Comment by karad** [comment]
@billrobertson42 Thank you for your comment. "That probrem" is about "A change between lein-figwheel 0.5.4 and lein-figwheel 0.5.5 causes it to barf with "There are errors in your configuration file"".
I think that you have to make new issue.
