### ISSUE TITLE
Provide configurability for Electron version

### ISSUE THREAD

**Issue by billrobertson42** [karad/lein_template_descjop#27]
It would be useful to be able to specify a specific version of Electron to target, perhaps via configuration settings in project.clj. This would allow developers to control this and get you out of the business of releasing updates whenever a new version of Electron is released.

**Comment by karad** [comment]
Thank you for your request. I think that descjop setting should be possible within project.clj, too.
But now, You can change Electron version in Gruntfile.js.

```
module.exports = function(grunt) {

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        "download-electron": {
            version: "1.3.2", // Electron version 1.3.2 -> 1.3.3
            outputDir: "./electron", 
            rebuild: true
        }
    });

    grunt.loadNpmTasks('grunt-download-electron');

};
```

and run

for linux / mac
```
$ lein descjop-init
```

for windows 
```
$ lein descjop-init-win
```

**Comment by billrobertson42** [comment]
I think that's sufficient. Maybe the result of this ticket should just be adding that information to the README.

**Comment by karad** [comment]
Ok. I released version.0.7.1. Added information of updating electron version.
